services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Tourze\RealNameAuthenticationBundle\Controller\:
    resource: '../../Controller/'
  Tourze\RealNameAuthenticationBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  Tourze\RealNameAuthenticationBundle\Repository\:
    resource: '../../Repository/'
  Tourze\RealNameAuthenticationBundle\Service\:
    resource: '../../Service/'
